# patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
spec:
  template:
    spec:
      containers:
      - name: server
        image: ghcr.io/podtato-head/podtatoserver:v0.1.1