kind: Simple
apiVersion: k3d.io/v1alpha2
name: ketch-demo
image: rancher/k3s:v1.20.4-k3s1
servers: 1
agents: 1
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
options:
  k3s:
    extraServerArgs:
    - --no-deploy=traefik
