name: podtato-head-microservices-tests

on:
  - push
  - pull_request

permissions:
  packages: write

env:
  CONTAINER_REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ github.token }}  
  GITHUB_USER: ${{ github.repository_owner }}
  
defaults:
  run:
    shell: bash

jobs:
  push_images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set custom tag/version
        if: github.ref_name != 'main'
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          if [[ "${BRANCH}" =~ 'release-' ]]; then
            # release branch: extracting version from branch name
            echo "VERSION=${BRANCH#'release-'}" >> $GITHUB_ENV
          # else
          #   consider adding something like this to isolate test tags
          #
          #   to ensure downstream tests still work, support for the ${VERSION}
          #   env var needs to be added to them too so that they can update
          #   image tags
          #
          #   echo "VERSION=test" >> ${GITHUB_ENV}
          fi
      - name: Push images
        run: make push-microservices-images 

  test_services:
    needs: push_images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test services
        run: make test-microservices